services:
 prometheus: # run the latest prometheus image
  image: prom/prometheus:latest
  # map server ports onto container ports
  ports:
   - "9090:9090"
  # map existing lcal config file onto container - will come in handy next
  volumes:
   - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
   - "prometheus-data:/prometheus"
 # tell prometheus where to expect config from
  command:
   - "--config.file=/etc/prometheus/prometheus.yml"
   - "--storage.tsdb.retention.time=7d" #don't want to max out storage!

 # hardware metrics
 node-exporter:
  image: prom/node-exporter:latest

  ports:
   - "9100:9100"

 # external website metrics
 blackbox-exporter:
  image: prom/blackbox-exporter:latest
  ports:
  - "9115:9115"
  volumes: # tell blackbox where to look for it's config file on my machine
  - "./blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml"
  command:
  - "--config.file=/etc/blackbox_exporter/config.yml"
 # internal webserver metrics
 nginx-exporter:
  image: nginx/nginx-prometheus-exporter:latest
  network_mode: host
  command:
  - "--nginx.scrape-uri=http://127.0.0.1:8080/nginx_status"

volumes:
  prometheus-data:
