# just copied from prometheus website for now
global:
  scrape_interval: 15s

scrape_configs:
- job_name: node
  static_configs:
  # this works because docker does clever internal DNS routing - scraping localhost is like scraping yourself!
  - targets: ['node-exporter:9100']
